<?php
/**
 * Datasheete.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Datasheete
 * @author Sascha Rösler <i-loko@t-online.de>.
 * @link http://github.com/sarom5
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Thu Mar 21 11:00:37 CET 2013.
 */

/**
 * Utility implementation class for list field entries related methods.
 */
class Datasheete_Util_ListEntries extends Datasheete_Util_Base_ListEntries
{
    /**
     * Get 'kind' list entries.
     *
     * @return array Array with desired list entries.
     */
    public function getKindEntriesForDatasheet()
    {
        $states = array();
        $states[] = array('value' => '1',
                          'text'  => $this->__('Widerstand'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '2 ',
                          'text'  => $this->__('Kondensator'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '3',
                          'text'  => $this->__('Diode'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '4',
                          'text'  => $this->__('Schottky Diode'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '5',
                          'text'  => $this->__('Signaldiode'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '6',
                          'text'  => $this->__('Transistor NPN'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '10',
                          'text'  => $this->__('Gleichrichterdiode'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '7',
                          'text'  => $this->__('Transistor PNP'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '8',
                          'text'  => $this->__('Leistungstransistor NPN'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '9',
                          'text'  => $this->__('Leistungstransistor PNP'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '11',
                          'text'  => $this->__('MOSFET NPN'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '12',
                          'text'  => $this->__('MOSFET PNP'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '13',
                          'text'  => $this->__('Optokoppler'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '14',
                          'text'  => $this->__('Mikrokontroller'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '15',
                          'text'  => $this->__('Latch Parallel -> Seriell'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '16',
                          'text'  => $this->__('Latch Seriell -> Parallel'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '17',
                          'text'  => $this->__('Gleichrichter'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '18',
                          'text'  => $this->__('Spannungsregler'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '19',
                          'text'  => $this->__('Logik IC'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '20',
                          'text'  => $this->__('LED'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '21',
                          'text'  => $this->__('Leistungs LED'),
                          'title' => '',
                          'image' => '');
    
        return $states;
    }
}
