<?php
/**
 * Datasheete.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Datasheete
 * @author Sascha Rösler <i-loko@t-online.de>.
 * @link http://github.com/sarom5
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Thu Mar 21 11:00:38 CET 2013.
 */

/**
 * This class provides object meta data for the Tag module.
 */
class Datasheete_TaggedObjectMeta_Datasheete extends Datasheete_TaggedObjectMeta_Base_Datasheete
{
    // feel free to extend the tag support here
}
