<?php
/**
 * Datasheete.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Datasheete
 * @author Sascha Rösler <i-loko@t-online.de>.
 * @link http://github.com/sarom5
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Thu Mar 21 11:00:38 CET 2013.
 */

/**
 * The datasheeteObjectState modifier displays the name of a given object's workflow state.
 * Examples:
 *    {$item.workflowState|datasheeteObjectState}       {* with led icon *}
 *    {$item.workflowState|datasheeteObjectState:false} {* no icon *}
 *
 * @param string  $state    Name of given workflow state.
 * @param boolean $withIcon Whether a led icon should be displayed before the name.
 *
 * @return string Enriched and translated workflow state ready for display.
 */
function smarty_modifier_datasheeteObjectState($state = 'initial', $withIcon = true)
{
    $serviceManager = ServiceUtil::getManager();
    $workflowHelper = new Datasheete_Util_Workflow($serviceManager);
    $stateInfo = $workflowHelper->getStateInfo($state);

    $result = $stateInfo['text'];
    if ($withIcon === true) {
        $result = '<img src="' . System::getBaseUrl() . 'images/icons/extrasmall/' . $stateInfo['icon'] . '" width="16" height="16" alt="' . $result . '" />&nbsp;&nbsp;' . $result;
    }

    return $result;
}
