<?php
/**
 * Datasheete.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Datasheete
 * @author Sascha Rösler <i-loko@t-online.de>.
 * @link http://github.com/sarom5
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Thu Mar 21 11:00:37 CET 2013.
 */

/**
 * This handler class handles the page events of the Form called by the datasheete_admin_edit() function.
 * It collects common functionality required by different object types.
 */
class Datasheete_Form_Handler_Admin_Edit extends Datasheete_Form_Handler_Admin_Base_Edit
{
    // feel free to extend the base handler class here
}
