<?php
/**
 * Datasheete.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Datasheete
 * @author Sascha Rösler <i-loko@t-online.de>.
 * @link http://github.com/sarom5
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Thu Mar 21 11:00:38 CET 2013.
 */

/**
 * Generic item list content plugin implementation class.
 */
class Datasheete_ContentType_ItemList extends Datasheete_ContentType_Base_ItemList
{
    // feel free to extend the content type here
}

function Datasheete_Api_ContentTypes_itemlist($args)
{
    return new Datasheete_Api_ContentTypes_itemListPlugin();
}
