<?php
/**
 * Datasheete.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Datasheete
 * @author Sascha Rösler <i-loko@t-online.de>.
 * @link http://github.com/sarom5
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Thu Mar 21 11:00:37 CET 2013.
 */

/**
 * Utility base class for list field entries related methods.
 */
class Datasheete_Util_Base_ListEntries extends Zikula_AbstractBase
{
    /**
     * Return the name or names for a given list item.
     *
     * @param string $value      The dropdown value to process.
     * @param string $objectType The treated object type.
     * @param string $fieldName  The list field's name.
     * @param string $delimiter  String used as separator for multiple selections.
     *
     * @return string List item name.
     */
    public function resolve($value, $objectType = '', $fieldName = '', $delimiter = ', ')
    {
        if (empty($value) || empty($objectType) || empty($fieldName)) {
            return $value;
        }
    
        $isMulti = $this->hasMultipleSelection($objectType, $fieldName);
        if ($isMulti === true) {
            $value = $this->extractMultiList($value);
        }
    
        $options = $this->getEntries($objectType, $fieldName);
        $result = '';
    
        if ($isMulti === true) {
            foreach ($options as $option) {
                if (!in_array($option['value'], $value)) {
                    continue;
                }
                if (!empty($result)) {
                    $result .= $delimiter;
                }
                $result .= $option['text'];
            }
        } else {
            foreach ($options as $option) {
                if ($option['value'] != $value) {
                    continue;
                }
                $result = $option['text'];
                break;
            }
        }
    
        return $result;
    }
    

    /**
     * Extract concatenated multi selection.
     *
     * @param string  $value The dropdown value to process.
     *
     * @return array List of single values.
     */
    public function extractMultiList($value)
    {
        $listValues = explode('###', $value);
        $numValues = count($listValues);
        if ($numValues > 1 && $listValues[$numValues-1] == '') {
            unset($listValues[$numValues-1]);
        }
        if ($listValues[0] == '') {
            unset($listValues[0]);
        }
    
        return $listValues;
    }
    

    /**
     * Determine whether a certain dropdown field has a multi selection or not.
     *
     * @param string $objectType The treated object type.
     * @param string $fieldName  The list field's name.
     *
     * @return boolean True if this is a multi list false otherwise.
     */
    public function hasMultipleSelection($objectType, $fieldName)
    {
        if (empty($objectType) || empty($fieldName)) {
            return false;
        }
    
        $result = false;
        switch ($objectType) {
            case 'datasheet':
                switch ($fieldName) {
                    case 'workflowState':
                        $result = false;
                        break;
                    case 'kind':
                        $result = false;
                        break;
                }
                break;
        }
    
        return $result;
    }
    

    /**
     * Get entries for a certain dropdown field.
     *
     * @param string  $objectType The treated object type.
     * @param string  $fieldName  The list field's name.
     *
     * @return array Array with desired list entries.
     */
    public function getEntries($objectType, $fieldName)
    {
        if (empty($objectType) || empty($fieldName)) {
            return array();
        }
    
        $entries = array();
        switch ($objectType) {
            case 'datasheet':
                switch ($fieldName) {
                    case 'workflowState':
                        $entries = $this->getWorkflowStateEntriesForDatasheet();
                        break;
                    case 'kind':
                        $entries = $this->getKindEntriesForDatasheet();
                        break;
                }
                break;
        }
    
        return $entries;
    }

    
    /**
     * Get 'workflow state' list entries.
     *
     * @return array Array with desired list entries.
     */
    public function getWorkflowStateEntriesForDatasheet()
    {
        $states = array();
        $states[] = array('value' => 'approved',
                          'text'  => $this->__('Approved'),
                          'title' => $this->__('Content has been approved and is available online.'),
                          'image' => '');
        $states[] = array('value' => '!approved',
                          'text'  => $this->__('All except approved'),
                          'title' => $this->__('Shows all items except these which are approved'),
                          'image' => '');
    
        return $states;
    }
    
    /**
     * Get 'kind' list entries.
     *
     * @return array Array with desired list entries.
     */
    public function getKindEntriesForDatasheet()
    {
        $states = array();
        $states[] = array('value' => '1',
                          'text'  => $this->__('Widerstand'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '2 ',
                          'text'  => $this->__('Kondensator'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '3',
                          'text'  => $this->__('Diode'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '4',
                          'text'  => $this->__('Schottky diode'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '5',
                          'text'  => $this->__('Signaldiode'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '6',
                          'text'  => $this->__('Transistor n p n'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '10',
                          'text'  => $this->__('Gleichrichterdiode'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '7',
                          'text'  => $this->__('Transistor p n p'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '8',
                          'text'  => $this->__('Leistungstransistor n p n'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '9',
                          'text'  => $this->__('Leistungstransistor p n p'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '11',
                          'text'  => $this->__('M o s f e t n p n'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '12',
                          'text'  => $this->__('M o s f e t p n p'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '13',
                          'text'  => $this->__('Optokoppler'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '14',
                          'text'  => $this->__('Mikrokontroller'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '15',
                          'text'  => $this->__('Latchparalleltoseriell'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '16',
                          'text'  => $this->__('Latchserielltoparallel'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '17',
                          'text'  => $this->__('Gleichrichter'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '18',
                          'text'  => $this->__('Spannungsregler'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '19',
                          'text'  => $this->__('Logik i c'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '20',
                          'text'  => $this->__('L e d'),
                          'title' => '',
                          'image' => '');
        $states[] = array('value' => '21',
                          'text'  => $this->__('Leistungs l e d'),
                          'title' => '',
                          'image' => '');
    
        return $states;
    }
}
