<?php
/**
 * Datasheete.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Datasheete
 * @author Sascha Rösler <i-loko@t-online.de>.
 * @link http://github.com/sarom5
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Thu Mar 21 11:00:36 CET 2013.
 */

/**
 * Installer base class.
 */
class Datasheete_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the Datasheete application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // Check if upload directories exist and if needed create them
        try {
            $controllerHelper = new Datasheete_Util_Controller($this->serviceManager);
            $result = $controllerHelper->checkAndCreateUploadFolder('datasheet', 'datasheet', 'gif, jpeg, jpg, png, pdf, doc, docx, odt, xls, ods');
            
        } catch (\Exception $e) {
            return LogUtil::registerError($e->getMessage());
        }
        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            $returnMessage = $this->__f('An error was encountered while creating the tables for the %s extension.', array($this->name));
            if (!System::isDevelopmentMode()) {
                $returnMessage .= ' ' . $this->__('Please enable the development mode by editing the /config/config.php file in order to reveal the error details.');
            }
            return LogUtil::registerError($returnMessage);
        }
    
        $categoryRegistryIdsPerEntity = array();
    
        // create the default data
        $this->createDefaultData($categoryRegistryIdsPerEntity);
    
        // register persistent event handlers
        $this->registerPersistentEventHandlers();
    
        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the Datasheete application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldVersion)
    {
    /*
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case 1.0.0:
                // do something
                // ...
                // update the database schema
                try {
                    DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
                } catch (\Exception $e) {
                    if (System::isDevelopmentMode()) {
                        LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
                    }
                    return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s extension.', array($this->getName())));
                }
        }
    */
    
        // update successful
        return true;
    }
    
    /**
     * Uninstall Datasheete.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s extension.', array($this->getName())));
        }
    
        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s extension.', array($this->name)));
        }
    
        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers($this->name);
    
        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // remove all thumbnails
        $manager = $this->getServiceManager()->getService('systemplugin.imagine.manager');
        $manager->setModule($this->name);
        $manager->cleanupModuleThumbs();
    
        // remind user about upload folders not being deleted
        $uploadPath = FileUtil::getDataDirectory() . '/' . $this->name . '/';
        LogUtil::registerStatus($this->__f('The upload directories at [%s] can be removed manually.', $uploadPath));
    
        // deletion successful
        return true;
    }
    
    /**
     * Build array with all entity classes for Datasheete.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'Datasheete_Entity_Datasheet';
    
        return $classNames;
    }
    
    /**
     * Create the default data for Datasheete.
     *
     * @param array $categoryRegistryIdsPerEntity List of category registry ids.
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        $entityClass = 'Datasheete_Entity_Datasheet';
        $this->entityManager->getRepository($entityClass)->truncateTable();
    }
    
    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core -> 
        EventUtil::registerPersistentModuleHandler('Datasheete', 'api.method_not_found', array('Datasheete_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'core.preinit', array('Datasheete_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'core.init', array('Datasheete_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'core.postinit', array('Datasheete_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'controller.method_not_found', array('Datasheete_Listener_Core', 'controllerMethodNotFound'));
    
        // front controller -> Datasheete_Listener_FrontController
        EventUtil::registerPersistentModuleHandler('Datasheete', 'frontcontroller.predispatch', array('Datasheete_Listener_FrontController', 'preDispatch'));
    
        // installer -> Datasheete_Listener_Installer
        EventUtil::registerPersistentModuleHandler('Datasheete', 'installer.module.installed', array('Datasheete_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'installer.module.upgraded', array('Datasheete_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'installer.module.uninstalled', array('Datasheete_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'installer.subscriberarea.uninstalled', array('Datasheete_Listener_Installer', 'subscriberAreaUninstalled'));
    
        // modules -> Datasheete_Listener_ModuleDispatch
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module_dispatch.postloadgeneric', array('Datasheete_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module_dispatch.preexecute', array('Datasheete_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module_dispatch.postexecute', array('Datasheete_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module_dispatch.custom_classname', array('Datasheete_Listener_ModuleDispatch', 'customClassname'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module_dispatch.service_links', array('Datasheete_Listener_ModuleDispatch', 'serviceLinks'));
    
        // mailer -> Datasheete_Listener_Mailer
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.mailer.api.sendmessage', array('Datasheete_Listener_Mailer', 'sendMessage'));
    
        // page -> Datasheete_Listener_Page
        EventUtil::registerPersistentModuleHandler('Datasheete', 'pageutil.addvar_filter', array('Datasheete_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'system.outputfilter', array('Datasheete_Listener_Page', 'systemOutputfilter'));
    
        // errors -> Datasheete_Listener_Errors
        EventUtil::registerPersistentModuleHandler('Datasheete', 'setup.errorreporting', array('Datasheete_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'systemerror', array('Datasheete_Listener_Errors', 'systemError'));
    
        // theme -> Datasheete_Listener_Theme
        EventUtil::registerPersistentModuleHandler('Datasheete', 'theme.preinit', array('Datasheete_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'theme.init', array('Datasheete_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'theme.load_config', array('Datasheete_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'theme.prefetch', array('Datasheete_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'theme.postfetch', array('Datasheete_Listener_Theme', 'postFetch'));
    
        // view -> Datasheete_Listener_View
        EventUtil::registerPersistentModuleHandler('Datasheete', 'view.init', array('Datasheete_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'view.postfetch', array('Datasheete_Listener_View', 'postFetch'));
    
        // user login -> Datasheete_Listener_UserLogin
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.users.ui.login.started', array('Datasheete_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.users.ui.login.veto', array('Datasheete_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.users.ui.login.succeeded', array('Datasheete_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.users.ui.login.failed', array('Datasheete_Listener_UserLogin', 'failed'));
    
        // user logout -> Datasheete_Listener_UserLogout
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.users.ui.logout.succeeded', array('Datasheete_Listener_UserLogout', 'succeeded'));
    
        // user -> Datasheete_Listener_User
        EventUtil::registerPersistentModuleHandler('Datasheete', 'user.gettheme', array('Datasheete_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'user.account.create', array('Datasheete_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'user.account.update', array('Datasheete_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'user.account.delete', array('Datasheete_Listener_User', 'delete'));
    
        // registration -> Datasheete_Listener_UserRegistration
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.users.ui.registration.started', array('Datasheete_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.users.ui.registration.succeeded', array('Datasheete_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.users.ui.registration.failed', array('Datasheete_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'user.registration.create', array('Datasheete_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'user.registration.update', array('Datasheete_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'user.registration.delete', array('Datasheete_Listener_UserRegistration', 'delete'));
    
        // users module -> Datasheete_Listener_Users
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.users.config.updated', array('Datasheete_Listener_Users', 'configUpdated'));
    
        // group -> Datasheete_Listener_Group
        EventUtil::registerPersistentModuleHandler('Datasheete', 'group.create', array('Datasheete_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'group.update', array('Datasheete_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'group.delete', array('Datasheete_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'group.adduser', array('Datasheete_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'group.removeuser', array('Datasheete_Listener_Group', 'removeUser'));
    
        // special purposes and 3rd party api support -> Datasheete_Listener_ThirdParty
        EventUtil::registerPersistentModuleHandler('Datasheete', 'get.pending_content', array('Datasheete_Listener_ThirdParty', 'pendingContentListener'));
        EventUtil::registerPersistentModuleHandler('Datasheete', 'module.content.gettypes', array('Datasheete_Listener_ThirdParty', 'contentGetTypes'));
    }
}
