<?php
/**
 * Datasheete.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Datasheete
 * @author Sascha Rösler <i-loko@t-online.de>.
 * @link http://github.com/sarom5
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Thu Mar 21 11:00:35 CET 2013.
 */

/**
 * Version information base class.
 */
class Datasheete_Base_Version extends Zikula_AbstractVersion
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '1.0.0';
        // the displayed name of the module
        $meta['displayname']          = $this->__('Datasheete');
        // the module description
        $meta['description']          = $this->__('Datasheete module generated by ModuleStudio 0.6.0.');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('datasheete');
        // core requirement
        $meta['core_min']             = '1.3.5'; // requires minimum 1.3.5
        $meta['core_max']             = '1.3.5'; // not ready for 1.3.6 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
                          HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true)
/*,
                          HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
                          'authentication' => array('version' => '1.0'),
                          'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
                          'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
*/
        );

        // permission schema
        $meta['securityschema'] = array(
            'Datasheete::' => '::',
            'Datasheete::Ajax' => '::',
            'Datasheete:ItemListBlock:' => 'Block title::',
            'Datasheete:Datasheet:' => 'Datasheet ID::',
        );
        // DEBUG: permission schema aspect ends


        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {
        
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.datasheete.ui_hooks.datasheets', 'ui_hooks', __('datasheete Datasheets Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'datasheete.ui_hooks.datasheets.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'datasheete.ui_hooks.datasheets.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'datasheete.ui_hooks.datasheets.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'datasheete.ui_hooks.datasheets.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'datasheete.ui_hooks.datasheets.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'datasheete.ui_hooks.datasheets.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'datasheete.ui_hooks.datasheets.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.datasheete.filter_hooks.datasheets', 'filter_hooks', __('datasheete Datasheets Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'datasheete.filter_hooks.datasheets.filter');
        $this->registerHookSubscriberBundle($bundle);

        
    }
}
