<?php
/**
 * Datasheete.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Datasheete
 * @author Sascha Rösler <i-loko@t-online.de>.
 * @link http://github.com/sarom5
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Thu Mar 21 11:00:36 CET 2013.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for datasheet entities.
 */
class Datasheete_Entity_Validator_Datasheet extends Datasheete_Entity_Validator_Base_Datasheet
{
    // here you can add custom validation methods or override existing checks
}
